ARG sourceimage=ck-quant
ARG sourcetag=local
FROM ${sourceimage}:${sourcetag}

COPY requirements-freqai.txt /freqtrade/
RUN pip install -r requirements-freqai.txt --user --no-cache-dir \
    --retries 10 --timeout 120
