name: Cleanup Packages

on:
  workflow_dispatch:
jobs:
  deploy-docker:
    name: "Delete Packages"
    runs-on: ubuntu-24.04
    if: github.repository == 'freqtrade/freqtrade'
    permissions:
      packages: write  # Needed to delete package versions

    steps:
    - name: "Delete untagged Package Versions"
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
      with:
        package-name: ${{ inputs.package_name || env.PACKAGE_NAME }}
        package-type: 'container'
        min-versions-to-keep: 10
        delete-only-untagged-versions: ${{ inputs.delete-untagged || 'true' }}
